2020-03-11 17:39:14,729 (15398/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-03-11 17:39:14,730 (15398/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-03-11 17:39:14,740 (15398/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 566, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 553, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 215, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 255, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-03-11 17:39:47,964 (15507/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-03-11 17:39:47,965 (15507/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-03-11 17:39:47,967 (15507/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 566, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 553, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 215, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 255, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-03-12 09:57:25,461 (5116/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-03-12 09:57:25,474 (5116/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-03-12 09:57:25,495 (5116/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 566, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/main.py", line 553, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 215, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 255, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/2.2.0_1/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
